# TODO: backend: health-check (and set depends_on for frontend)

services:
  frontend:
    container_name: muse-frontend
    build:
      context: ../frontend/
      dockerfile: ./deploy/dev.Dockerfile
    volumes:
      - ../frontend:/app
    networks:
      - net
    ports:
      - "3000:3000"
    restart: on-failure

  backend:
    container_name: muse-backend
    build:
      context: ../backend/
      dockerfile: ./deploy/dev.Dockerfile
    env_file:
      - ../config/backend.env
    volumes:
      - ../backend:/app
    networks:
      - net
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    container_name: muse-postgres
    image: postgres:18-alpine
    env_file:
      - ../config/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.12
    env_file:
      - ../config/pgadmin.env
    ports:
      - "8000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - net
    restart: on-failure

volumes:
  postgres_data:
  pgadmin_data:

networks:
  net:
    name: net
    driver: bridge
